CREATE TABLE regions (
    region_id   BIGINT NOT NULL,
    region_name VARCHAR(100),

    CONSTRAINT pk_regions PRIMARY KEY (region_id)
);


CREATE TABLE countries (
    country_id   VARCHAR(5)  NOT NULL,
    country_name VARCHAR(100) NOT NULL,
    region_id    BIGINT,

    CONSTRAINT pk_countries PRIMARY KEY (country_id),
    CONSTRAINT fk_countries_region
        FOREIGN KEY (region_id)
        REFERENCES regions (region_id)
);

CREATE INDEX idx_countries_region_id
ON countries (region_id);

CREATE TABLE locations (
    location_id     BIGINT NOT NULL,
    street_address  VARCHAR(255),
    postal_code     VARCHAR(20),
    city            VARCHAR(100),
    state_province  VARCHAR(100),
    country_id      VARCHAR(5),

    CONSTRAINT pk_locations PRIMARY KEY (location_id),
    CONSTRAINT fk_locations_country
        FOREIGN KEY (country_id)
        REFERENCES countries (country_id)
);

CREATE INDEX idx_locations_country_id
ON locations (country_id);


CREATE TABLE departments (
    department_id   BIGINT NOT NULL,
    department_name VARCHAR(255) NOT NULL,
    location_id     BIGINT,

    CONSTRAINT pk_departments PRIMARY KEY (department_id),
    CONSTRAINT fk_departments_location
        FOREIGN KEY (location_id)
        REFERENCES locations (location_id)
);

CREATE INDEX idx_departments_location_id
ON departments (location_id);


CREATE TABLE jobs (
    job_id      VARCHAR(20) NOT NULL,
    job_title   VARCHAR(150) NOT NULL,

    CONSTRAINT pk_jobs PRIMARY KEY (job_id)
);

CREATE TABLE employees (
    employee_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name      VARCHAR(100),
    last_name       VARCHAR(100) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    phone_number    VARCHAR(20),
    hire_date       DATE NOT NULL,
    job_id          VARCHAR(20),
    salary          NUMERIC(8,2),
    manager_id      BIGINT,
    department_id   BIGINT,

    CONSTRAINT pk_employees PRIMARY KEY (employee_id),
    CONSTRAINT uq_employees_email UNIQUE (email),

    CONSTRAINT fk_employees_job
        FOREIGN KEY (job_id)
        REFERENCES jobs (job_id),

    CONSTRAINT fk_employees_department
        FOREIGN KEY (department_id)
        REFERENCES departments (department_id),

    CONSTRAINT fk_employees_manager
        FOREIGN KEY (manager_id)
        REFERENCES employees (employee_id)
);

CREATE INDEX idx_employees_department_id
ON employees (department_id);

CREATE INDEX idx_employees_job_id
ON employees (job_id);

CREATE INDEX idx_employees_manager_id
ON employees (manager_id);


CREATE TABLE job_history (
    employee_id   BIGINT NOT NULL,
    start_date    DATE NOT NULL,
    end_date      DATE,
    job_id        VARCHAR(20) NOT NULL,
    department_id BIGINT,

    CONSTRAINT pk_job_history
        PRIMARY KEY (employee_id, start_date),

    CONSTRAINT fk_jh_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id),

    CONSTRAINT fk_jh_job
        FOREIGN KEY (job_id)
        REFERENCES jobs (job_id),

    CONSTRAINT fk_jh_department
        FOREIGN KEY (department_id)
        REFERENCES departments (department_id)
);

CREATE INDEX idx_jh_job_id
ON job_history (job_id);

CREATE INDEX idx_jh_department_id
ON job_history (department_id);
