INSERT INTO countries (country_id, country_name, region_id) VALUES
-- Africa (1)
('DZ', 'Algeria', 1),
('AO', 'Angola', 1),
('BJ', 'Benin', 1),
('BW', 'Botswana', 1),
('BF', 'Burkina Faso', 1),
('BI', 'Burundi', 1),
('CM', 'Cameroon', 1),
('CV', 'Cape Verde', 1),
('CF', 'Central African Republic', 1),
('TD', 'Chad', 1),
('KM', 'Comoros', 1),
('CG', 'Congo', 1),
('CD', 'Congo, Democratic Republic', 1),
('DJ', 'Djibouti', 1),
('EG', 'Egypt', 1),
('GQ', 'Equatorial Guinea', 1),
('ER', 'Eritrea', 1),
('SZ', 'Eswatini', 1),
('ET', 'Ethiopia', 1),
('GA', 'Gabon', 1),
('GM', 'Gambia', 1),
('GH', 'Ghana', 1),
('GN', 'Guinea', 1),
('GW', 'Guinea-Bissau', 1),
('CI', 'Ivory Coast', 1),
('KE', 'Kenya', 1),
('LS', 'Lesotho', 1),
('LR', 'Liberia', 1),
('LY', 'Libya', 1),
('MG', 'Madagascar', 1),
('MW', 'Malawi', 1),
('ML', 'Mali', 1),
('MR', 'Mauritania', 1),
('MU', 'Mauritius', 1),
('MA', 'Morocco', 1),
('MZ', 'Mozambique', 1),
('NA', 'Namibia', 1),
('NE', 'Niger', 1),
('NG', 'Nigeria', 1),
('RW', 'Rwanda', 1),
('ST', 'Sao Tome and Principe', 1),
('SN', 'Senegal', 1),
('SC', 'Seychelles', 1),
('SL', 'Sierra Leone', 1),
('SO', 'Somalia', 1),
('ZA', 'South Africa', 1),
('SS', 'South Sudan', 1),
('SD', 'Sudan', 1),
('TZ', 'Tanzania', 1),
('TG', 'Togo', 1),
('TN', 'Tunisia', 1),
('UG', 'Uganda', 1),
('ZM', 'Zambia', 1),
('ZW', 'Zimbabwe', 1),

-- Antarctica (2)
('AQ', 'Antarctica', 2),

-- Asia (3)
('AF', 'Afghanistan', 3),
('AM', 'Armenia', 3),
('AZ', 'Azerbaijan', 3),
('BH', 'Bahrain', 3),
('BD', 'Bangladesh', 3),
('BT', 'Bhutan', 3),
('BN', 'Brunei', 3),
('KH', 'Cambodia', 3),
('CN', 'China', 3),
('CY', 'Cyprus', 3),
('GE', 'Georgia', 3),
('IN', 'India', 3),
('ID', 'Indonesia', 3),
('IR', 'Iran', 3),
('IQ', 'Iraq', 3),
('IL', 'Israel', 3),
('JP', 'Japan', 3),
('JO', 'Jordan', 3),
('KZ', 'Kazakhstan', 3),
('KW', 'Kuwait', 3),
('KG', 'Kyrgyzstan', 3),
('LA', 'Laos', 3),
('LB', 'Lebanon', 3),
('MY', 'Malaysia', 3),
('MV', 'Maldives', 3),
('MN', 'Mongolia', 3),
('MM', 'Myanmar', 3),
('NP', 'Nepal', 3),
('KP', 'North Korea', 3),
('OM', 'Oman', 3),
('PK', 'Pakistan', 3),
('PS', 'Palestine', 3),
('PH', 'Philippines', 3),
('QA', 'Qatar', 3),
('SA', 'Saudi Arabia', 3),
('SG', 'Singapore', 3),
('KR', 'South Korea', 3),
('LK', 'Sri Lanka', 3),
('SY', 'Syria', 3),
('TJ', 'Tajikistan', 3),
('TH', 'Thailand', 3),
('TL', 'Timor-Leste', 3),
('TM', 'Turkmenistan', 3),
('AE', 'United Arab Emirates', 3),
('UZ', 'Uzbekistan', 3),
('VN', 'Vietnam', 3),
('YE', 'Yemen', 3),

-- Europe (4)
('AL', 'Albania', 4),
('AD', 'Andorra', 4),
('AT', 'Austria', 4),
('BY', 'Belarus', 4),
('BE', 'Belgium', 4),
('BA', 'Bosnia and Herzegovina', 4),
('BG', 'Bulgaria', 4),
('HR', 'Croatia', 4),
('CZ', 'Czechia', 4),
('DK', 'Denmark', 4),
('EE', 'Estonia', 4),
('FI', 'Finland', 4),
('FR', 'France', 4),
('DE', 'Germany', 4),
('GR', 'Greece', 4),
('HU', 'Hungary', 4),
('IS', 'Iceland', 4),
('IE', 'Ireland', 4),
('IT', 'Italy', 4),
('LV', 'Latvia', 4),
('LI', 'Liechtenstein', 4),
('LT', 'Lithuania', 4),
('LU', 'Luxembourg', 4),
('MT', 'Malta', 4),
('MD', 'Moldova', 4),
('MC', 'Monaco', 4),
('ME', 'Montenegro', 4),
('NL', 'Netherlands', 4),
('MK', 'North Macedonia', 4),
('NO', 'Norway', 4),
('PL', 'Poland', 4),
('PT', 'Portugal', 4),
('RO', 'Romania', 4),
('RU', 'Russia', 4),
('SM', 'San Marino', 4),
('RS', 'Serbia', 4),
('SK', 'Slovakia', 4),
('SI', 'Slovenia', 4),
('ES', 'Spain', 4),
('SE', 'Sweden', 4),
('CH', 'Switzerland', 4),
('TR', 'Turkey', 4),
('UA', 'Ukraine', 4),
('GB', 'United Kingdom', 4),

-- North America (5)
('AG', 'Antigua and Barbuda', 5),
('BS', 'Bahamas', 5),
('BB', 'Barbados', 5),
('BZ', 'Belize', 5),
('CA', 'Canada', 5),
('CR', 'Costa Rica', 5),
('CU', 'Cuba', 5),
('DM', 'Dominica', 5),
('DO', 'Dominican Republic', 5),
('SV', 'El Salvador', 5),
('GL', 'Greenland', 5),
('GD', 'Grenada', 5),
('GT', 'Guatemala', 5),
('HT', 'Haiti', 5),
('HN', 'Honduras', 5),
('JM', 'Jamaica', 5),
('MX', 'Mexico', 5),
('NI', 'Nicaragua', 5),
('PA', 'Panama', 5),
('KN', 'Saint Kitts and Nevis', 5),
('LC', 'Saint Lucia', 5),
('VC', 'Saint Vincent and the Grenadines', 5),
('TT', 'Trinidad and Tobago', 5),
('US', 'United States', 5),

-- South America (6)
('AR', 'Argentina', 6),
('BO', 'Bolivia', 6),
('BR', 'Brazil', 6),
('CL', 'Chile', 6),
('CO', 'Colombia', 6),
('EC', 'Ecuador', 6),
('GY', 'Guyana', 6),
('PY', 'Paraguay', 6),
('PE', 'Peru', 6),
('SR', 'Suriname', 6),
('UY', 'Uruguay', 6),
('VE', 'Venezuela', 6),

-- Australia / Oceania (7)
('AU', 'Australia', 7),
('FJ', 'Fiji', 7),
('KI', 'Kiribati', 7),
('MH', 'Marshall Islands', 7),
('FM', 'Micronesia', 7),
('NR', 'Nauru', 7),
('NZ', 'New Zealand', 7),
('PW', 'Palau', 7),
('PG', 'Papua New Guinea', 7),
('WS', 'Samoa', 7),
('SB', 'Solomon Islands', 7),
('TO', 'Tonga', 7),
('TV', 'Tuvalu', 7),
('VU', 'Vanuatu', 7);
